//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string productID { get; set; }
        public string shopID { get; set; }
        public string productName { get; set; }
        public string productContent { get; set; }
        public Nullable<int> productQuantity { get; set; }
        public Nullable<double> productPrice { get; set; }
    
        public virtual shopOwner shopOwner { get; set; }
    }
}
